### ISSUE TITLE
Add requirements and Dockerfile

### ISSUE THREAD

**Issue by Nicholas-Polimeni** [Urban-Research-Group/ga-tax-assessment#18]

**Comment by Nicholas-Polimeni** [comment]
92.19   Preparing metadata (pyproject.toml): started
92.86   Preparing metadata (pyproject.toml): finished with status 'error'
92.86   error: subprocess-exited-with-error
92.86
92.86   × Preparing metadata (pyproject.toml) did not run successfully.
92.86   │ exit code: 2
92.86   ╰─> [80 lines of output]
92.86       + meson setup /tmp/pip-install-n7jf0_94/pandas_0b38c3c76e6447cda64f3ac59f62f24e /tmp/pip-install-n7jf0_94/pandas_0b38c3c76e6447cda64f3ac59f62f24e/.mesonpy-spgk1rhl/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-n7jf0_94/pandas_0b38c3c76e6447cda64f3ac59f62f24e/.mesonpy-spgk1rhl/build/meson-python-native-file.ini
92.86       Traceback (most recent call last):
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/mesonmain.py", line 194, in run
92.86           return options.run_func(options)
92.86                  ~~~~~~~~~~~~~~~~^^^^^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/msetup.py", line 358, in run
92.86           app.generate()
92.86           ~~~~~~~~~~~~^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/msetup.py", line 183, in generate
92.86           return self._generate(env, capture, vslite_ctx)
92.86                  ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/msetup.py", line 228, in _generate
92.86           intr.run()
92.86           ~~~~~~~~^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreter/interpreter.py", line 2997, in run
92.86           super().run()
92.86           ~~~~~~~~~~~^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 164, in run
92.86           self.evaluate_codeblock(self.ast, start=1)
92.86           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
92.86           raise e
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
92.86           self.evaluate_statement(cur)
92.86           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 198, in evaluate_statement
92.86           self.assignment(cur)
92.86           ~~~~~~~~~~~~~~~^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 635, in assignment
92.86           value = self.evaluate_statement(node.value)
92.86                   ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
92.86           return self.method_call(cur)
92.86                  ~~~~~~~~~~~~~~~~^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 550, in method_call
92.86           res = obj.method_call(method_name, args, kwargs)
92.86                 ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreter/interpreterobjects.py", line 811, in method_call
92.86           ret = method(state, args, kwargs)
92.86                 ~~~~~~^^^^^^^^^^^^^^^^^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/decorators.py", line 109, in wrapped
92.86           ret = f(*wrapped_args, **wrapped_kwargs)
92.86                 ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
92.86           return f(*nargs, **wrapped_kwargs)
92.86                  ~^^^^^^^^^^^^^^^^^^^^^^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/decorators.py", line 596, in wrapper
92.86           return f(*wrapped_args, **wrapped_kwargs)
92.86                  ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/modules/python.py", line 437, in find_installation
92.86           python = self._find_installation_impl(state, display_name, name_or_path, required)
92.86                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/modules/python.py", line 393, in _find_installation_impl
92.86           if python.sanity(state):
92.86              ~~~~~~~~~~~~~^^^^^^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/modules/python.py", line 74, in sanity
92.86           ret = super().sanity()
92.86                 ~~~~~~~~~~~~~~^^
92.86         File "/tmp/pip-build-env-fx9_ows6/overlay/lib/python3.13/site-packages/mesonbuild/dependencies/python.py", line 114, in sanity
92.86           with importlib.resources.path('mesonbuild.scripts', 'python_info.py') as f:
92.86                ^^^^^^^^^^^^^^^^^^^^^^^^
92.86       AttributeError: module 'importlib.resources' has no attribute 'path'
92.86       The Meson build system
92.86       Version: 1.2.1
92.86       Source dir: /tmp/pip-install-n7jf0_94/pandas_0b38c3c76e6447cda64f3ac59f62f24e
92.86       Build dir: /tmp/pip-install-n7jf0_94/pandas_0b38c3c76e6447cda64f3ac59f62f24e/.mesonpy-spgk1rhl/build
92.86       Build type: native build
92.86       Project name: pandas
92.86       Project version: 2.1.4
92.86       C compiler for the host machine: cc (gcc 13.2.1 "cc (Alpine 13.2.1_git20231014) 13.2.1 20231014")
92.86       C linker for the host machine: cc ld.bfd 2.41
92.86       C++ compiler for the host machine: c++ (gcc 13.2.1 "c++ (Alpine 13.2.1_git20231014) 13.2.1 20231014")
92.86       C++ linker for the host machine: c++ ld.bfd 2.41
92.86       Cython compiler for the host machine: cython (cython 0.29.37)
92.86       Host machine cpu family: x86_64
92.86       Host machine cpu: x86_64
92.86
92.86       ../../meson.build:15:22: ERROR: Unhandled python exception
92.86
92.86           This is a Meson bug and should be reported!
92.86       [end of output]
92.86
92.86   note: This error originates from a subprocess, and is likely not a problem with pip.
92.86 error: metadata-generation-failed
92.86
92.86 × Encountered error while generating package metadata.
92.86 ╰─> See above for output.
92.86
92.86 note: This is an issue with the package mentioned above, not pip.
92.86 hint: See above for details.
------
dockerfile:15
--------------------
  13 |     ADD . /src
  14 |
  15 | >>> RUN pip install --no-cache-dir -r requirements.txt
  16 |
  17 |     EXPOSE 80
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
